### ISSUE TITLE
Some shows with year parentheses not properly updated.

### ISSUE THREAD

**Issue by g-mos** [maximeh/script.myepisodes#11]
There are some seriels (eg. Scandal, Hawaii Five-0) that have a year value in only one of the two sides (Scandal in my side, HF0 in the myepisode side). Is it acceptable to completely discard the year value in the searches? If needed I can provide a code patch.

**Comment by maximeh** [comment]
Hey,

If you have some code that fixes that, I'd be happy to see it.

A good test also, is does it work with Doctor Who ? Because there's the old show 'Doctor Who' and the new one 'Docto Who (2005)', so you can't really drop the year altogether.

IIRC, what is currently implemented is that it checks if the show exists in your profile, if it does, it selects it. So even if Scandal has the year, as long as you have the right show in your profile in myepisode, you should be good to go. But maybe there's bug in there...

**Comment by g-mos** [comment]
Hey,
You are right about series as Doctor Who. As it seems I have to see exactly what your programm does first before I come back with a suggestion. A proper 4 step check would be:
1. Check my series with the year
2. Check my series without year
3. Chech for new series with the year
4. Check for new series without year

Of course you move to the next step if the previous fails. I will return with more details in some days.

**Comment by maximeh** [comment]
@g-mos ping ?

**Comment by g-mos** [comment]
Sorry I did not have time to properly check it. We can close it for now and if I have time and a proper debugin I will return.

**Comment by maximeh** [comment]
No problem. As fas as I can tell it's working pretty good for me, but if you still have issues, feel free to open a new one.
